### ISSUE TITLE
Original schematic has an error

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Arcade-BombJack_MiSTer#20]
If this core was made by using the original schematics you should robably check this:

Martin Piper wrote on Twitter that the schematics has an error:

"page 6 character screen logic
IC 2R pin 6 should not connect to 8C pin 4"

Source: 
https://twitter.com/MartinPiper/status/1458668350796566529

**Comment by paulb-nl** [comment]
Thanks. It is related to CPU access to character data. It does not affect this core so this can be closed.
