### ISSUE TITLE
Sprite issue at top of screen when jumping

### ISSUE THREAD

**Issue by Spazmoid1981** [MiSTer-devel/Arcade-BombJack_MiSTer#21]
Seems like there is a sprite issue where the top pixel appears corrupted when you jump to the very top of the play area - Anyone know how to fix this?

**Comment by Spazmoid1981** [comment]
@sorgelig can you see any fix here for this or why it would happen?

**Comment by paich64** [comment]
@sorgelig this core has just been ported to Mega65 using MisterToM65 framework and indeed we have also this issue. Just in case you would have time to look at it :)

**Comment by sorgelig** [comment]
I only ported this core. I don't know original schematics.
