### ISSUE TITLE
Rotating screen should not rotate joystick

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Arcade-BombJack_MiSTer#9]
When you rotate the screen in the menu AND your physical monitor, the joystick directions right/left/up/down are suddenly wrong - even when you remap the joystick. The only way to make it work is to remap pressing _down_ when the mapping asks for RIGHT - and _up_ when it asks for LEFT.

**Comment by paulb-nl** [comment]
Joystick rotation has been removed a few years ago so this can be closed.
